### ISSUE TITLE
add --settings for runserver or runserver_plus

### ISSUE THREAD

**Issue by applewebbo** [oliverandrich/django-tailwind-cli#101]
I'm experimenting with your work and I find it amazing, thanks. 

I normally use separate settings files for development, production and what I normally type in the terminal is something like this:

`python manage.py runserver_plus --settings=<project_name>.settings.development`

If I try to use your script to run both server_plus and tailwind like this:

`python manage.py tailwind runserver_plus --settings=<project_name>.settings.development`

It won't work because (as I understand) you need to add a parser for passing --settings=<project_name>.settings.development to runserver_plus. I know I can use two separate scripts but it will be great if you can add it to the single script. Please let me know if this is possible and you plan to add it in future release.

Thanks a lot for your work.. I appreciate it a lot

**Comment by oliverandrich** [comment]
This sounds like a good idea. I will add it to the next version, which is planned to be released at the end of the month.

**Comment by applewebbo** [comment]
Great! Thank you

**Comment by oliverandrich** [comment]
This might end in a complete rewrite of the management command suite of this package. I find it rather annoying that I have to duplicate the argument parsers of runserver and runserver_plus just to use it as a subcommand of the `tailwind` command.

Option 1: Get rid of the `tailwind` subcommand and provide commands with a syntax like `tailwind_build`, `tailwind_build`, `tailwind_runserver`, `tailwind_runserver_plus`.
Option 2: I find an easy way to call the handle methods of the runserver and runserver_plus commands.

Option 2 is the preferred way.

**Comment by oliverandrich** [comment]
@applewebbo I have a question.

```
./manage.py tailwind --settings=... runserver_plus 
```

Does this work for you with the current version?

**Comment by applewebbo** [comment]
it works!

```
❯ python manage.py tailwind --settings=uv_test.settings.development runserver_plus


You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8000
Press CTRL+C to quit
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

Django version 5.0.2, using settings 'uv_test.settings.development'
Development server is running at http://[127.0.0.1]:8000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 481-291-159

Rebuilding...

Done in 686ms.
```

**Comment by oliverandrich** [comment]
Okay, then I would prefer to stick to this standard for sub commands, if this is okay for you. But I did rework the management command anyway for an upcoming release. Just have to puit some finishing touches to it.

**Comment by applewebbo** [comment]
For me it's ok to stick to this syntax. Thanks for your time working on this.
