### ISSUE TITLE
tailwind download

### ISSUE THREAD

**Issue by jefftriplett** [oliverandrich/django-tailwind-cli#109]
It would be helpful if `_download_cli_if_not_exists` was exposed as an optional `tailwind download` sub-command. 

This would make it possible in a Dockerfile to download the binary (without architecture hoops) when the image is built so that it's not later downloaded when the `tailwind build` command is run. 

I currently run `python -m manage tailwind --skip-checks build` in my Dockerfile, which is fine to get the binary file installed, but it tends to create a bunch of extra layers that seem to add up rather quickly.

**Comment by oliverandrich** [comment]
Sounds like a good idea. I will add it.

**Comment by oliverandrich** [comment]
Added a "download_cli" subcommand to handle this request. Before releasing it, I need to add some documentation and also want to refactor some parts of the management command in general.

**Comment by jefftriplett** [comment]
🎉  Thank you for the quick reply and feature addition.

**Comment by oliverandrich** [comment]
`download_cli` is part of 2.10.0 released today.
