### ISSUE TITLE
Custom URL for tailwind download URL

### ISSUE THREAD

**Issue by Tobi-De** [oliverandrich/django-tailwind-cli#128]
Hi @oliverandrich,

Hope you're doing great.

Would you accept a PR that makes the [download URL](https://github.com/oliverandrich/django-tailwind-cli/blob/main/src/django_tailwind_cli/utils.py#L73) configurable via Django settings?

```python
    @property
    def base_download_url(self) -> str:
        return getattr(settings, "TAILWIND_CLI_BASE_DOWNOAD_URL_FILE", "https://github.com/tailwindlabs/tailwindcss/releases/download/")

    def get_download_url(self) -> str:
        """Get the download url for the Tailwind CSS CLI."""
        system, machine = self.get_system_and_machine()
        extension = ".exe" if system == "windows" else ""
        return (
            self.base_download_url,
            f"v{self.tailwind_version}/tailwindcss-{system}-{machine}{extension}"
        )
```

I want to use [this package](https://github.com/dobicinaitis/tailwind-cli-extra), which includes the Tailwind CLI with DaisyUI. Eventually, I could  even repackage the CLI with additional plugins myself as described [here](https://github.com/tailwindlabs/tailwindcss/discussions/12294). It would be awesome if we could specify where to download the CLI from. Thanks

**Comment by oliverandrich** [comment]
Hi @Tobi-De, sounds like a good addition to the library. I would be happy to merge a pull request for that. Is #129 complete and can I merge it?

**Comment by Tobi-De** [comment]
> Hi @Tobi-De, sounds like a good addition to the library. I would be happy to merge a pull request for that. Is #129 complete and can I merge it?

In my opinion yes

**Comment by Tobi-De** [comment]
I should add, I wasn't able to run the test locally but I highly doubt this would impact any existing feature

**Comment by Tobi-De** [comment]
Added in #129
