### ISSUE TITLE
I am working on a Awesome-Python-HTMX, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [oliverandrich/django-tailwind-cli#25]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create awesome-python-htmx; a collection of active tools/libraries/projects in that space (including Tailwind). I have included your project a section listing tooling.

If you could also participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated! I would in particular be interested to hear about sets your tailwind Python tooling apart from the alternatives.

**Comment by oliverandrich** [comment]
@benjamin-kirkbride Thanks for reaching out to me and adding me to the list. I left a comment on the issue you mentioned.

Where should I drop the information what is the main difference between django-tailwind and my django-tailwind-cli?

**Comment by benjamin-kirkbride** [comment]
You are welcome to make a PR to expand the section under your project :) 

I'd ask:
1. That you try to keep it to a paragraph or less, so people aren't overwhelmed with huge descriptions of each project, and
2. That you try to keep the info relatively in sync with the intro to your project on your README; if you want to call out the differences, do it in both places.

Does that make sense/seem reasonable?

**Comment by oliverandrich** [comment]
The entry on the package looks for me.
