### ISSUE TITLE
django_extensions runserver_plus option?

### ISSUE THREAD

**Issue by wshayes** [oliverandrich/django-tailwind-cli#53]
Great tool. It makes developing with Django and Tailwind much easier. 

Would it be possible to add an option for runserver_plus from django extensions (to be able to run SSL for localdev)?

I'm happy to take a stab at creating a pull request for this, but I wanted to run it past you first in case you didn't want to do this.

**Comment by oliverandrich** [comment]
This sounds like a good idea. I am happy to merge a pull request. Maybe it is a good idea to add django-extensions as an optional dependency? And I hope you are aware, that I switched back to poetry. I am mentioning this just in case you found the repo after reading my blogpost about hatch.
