### ISSUE TITLE
Update Windows Tailwind executable download path

### ISSUE THREAD

**Issue by rtr1** [oliverandrich/django-tailwind-cli#67]
Hello. When I run `python .\manage.py tailwind runserver` I get the message:

> Tailwind CSS CLI not found.
> Downloading Tailwind CSS CLI from 'https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.5/tailwindcss-windows-amd64'

Which errors with 404 not found. The download link in [Tailwind Labs repository](https://github.com/tailwindlabs/tailwindcss/releases) is:

> https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.5/tailwindcss-windows-x64.exe

With the differences being:

- `x64` instead of `amd64`
- Includes `.exe` suffix

If I update these two functions it downloads the correct Tailwind CLI executable:

```python
def get_system_and_machine(self) -> Tuple[str, str]:
    """Get the system and machine name."""
    system = platform.system().lower()
    if system == "darwin":  # pragma: no cover
        system = "macos"

    machine = platform.machine().lower()
    if machine == "x86_64" or 'amd64':  # pragma: no cover
        machine = "x64"
    elif machine == "aarch64":  # pragma: no cover
        machine = "arm64"

    return (system, machine)

def get_download_url(self) -> str:
    """Get the download url for the Tailwind CSS CLI."""
    system, machine = self.get_system_and_machine()
    extension = '.exe' if system == 'windows' else ''
    return (
        "https://github.com/tailwindlabs/tailwindcss/releases/download/"
        f"v{self.tailwind_version}/tailwindcss-{system}-{machine}{extension}"
    )
```

With the changes being:

- Add `or 'amd64'` to `if machine == "x86_64" or 'amd64':`
- Add `extension = '.exe' if system == 'windows' else ''`
- Update the f-string to include the `{extension}`

I'm using Python 3.11.3 64-bit on Windows 11 with Django 4.2.4

**Comment by oryon-dominik** [comment]
It also has issues recognizing `tailwindcss.exe` when installed via `scoop` (linked in `~/scoop/shims/` by default)

**Comment by oliverandrich** [comment]
@rtr1 I plan to work on this issue on Friday. I would be happy to see someone let the test suite run on Windows, as I only have Macs and Linux machines at hand. Could you do this for me?

**Comment by oliverandrich** [comment]
@oryon-dominik I think you are referencing to the same topic as Jeff did in his discussion entry (https://github.com/oliverandrich/django-tailwind-cli/discussions/65). I plan to add the functionality to reference an externally installed CLI. I will create a seperate ticket for this.
