### ISSUE TITLE
`tailwind runserver` isn't passing through `--skip-checks`

### ISSUE THREAD

**Issue by jefftriplett** [oliverandrich/django-tailwind-cli#69]
I'm currently running `python manage.py tailwind --skip-checks runserver 0.0.0.0:8000` and I noticed it was taking between 7 to 10 seconds to scan+reload Python code changes. 

I checked my logs and noticed `Performing system checks...` which is a sign that `--skip-checks` isn't being respected/passed to runserver. 

Frustratingly, this is a common performance issue for medium to large projects in containers. 

if `--skip-checks` could either get passed through or added as an options to `runserver` then it should just work via: `python manage.py tailwind runserver --skip-checks 0.0.0.0:8000`. 

Is there any interest in adding this? I might be able to take it on Friday if so. (assuming someone doesn't beat me to it :) )

**Comment by oliverandrich** [comment]
Good idea. As I also plan to work a bit on the project on Friday, I can fix this easily.

**Comment by jefftriplett** [comment]
@oliverandrich danke 🎉
