### ISSUE TITLE
adding plugins from node_modules

### ISSUE THREAD

**Issue by jcuotpc** [oliverandrich/django-tailwind-cli#75]
I wonder if there is an easy way to add additional npm packages as plugins to this app.
For example I would like to integrate daisyui with django-tailwind-cli and don't know how to start...

Any hint would be very helpful.

**Comment by oliverandrich** [comment]
This library is intentionally not capable to manage tailwind plugins besides the standard plugins delivered along with the official CLI.

But starting with version `2.7.0` you can point your configuration to a globally installed version of the tailwindcss CLI. As far as I good explore it, this works for me.

**Step 1:** Install tailwindcss and daisyui globally

```shell
npm install -g tailwindcss
npm install -g daisyui
```

**Step 2:** Configure django-tailwind-cli to use this version of tailwindcss CLI

Add this to your settings.py. I assume it is installed in /usr/local/bin, but this can be any other path too. This depends on your OS, setup and so on.

```python
TAILWIND_CLI_PATH="/usr/local/bin/tailwindcss"
TAILWIND_CLI_AUTOMATIC_DOWNLOAD=False
```

Afterwards you should be able to add the daisyui plugin to the tailwind.config.js created by django-tailwind-cli initially.

**Comment by oliverandrich** [comment]
I close this issue for the moment, as I consider the question answered.
