### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by naresh-kapsus** [oliverandrich/django-tailwind-cli#95]
I am trying to use the plugin but while run **python manage.py tailwind watch** i got the following error
subprocess.CalledProcessError: Command '['/home/<user_name>/.local/bin/tailwindcss-linux-x64-3.4.0', '--output', '/var/www/html/django_new/assets/css/tailwind.css', '--watch']' died with <Signals.SIGSEGV: 11>. any help will be appreciated

**Comment by oliverandrich** [comment]
Sometimes I see, that the binary is broken after download. What is the output of `/home/<user_name>/.local/bin/tailwindcss-linux-x64-3.4.0` in a normal shell? Does this work?

**Comment by naresh-kapsus** [comment]
> Sometimes I see, that the binary is broken after download. What is the output of `/home/<user_name>/.local/bin/tailwindcss-linux-x64-3.4.0` in a normal shell? Does this work?

The output of the same is "Segmentation fault"

**Comment by oliverandrich** [comment]
Okay, then it is not a problem of the module but the tailwind cli is broken. I would suggest to manually remove it and let the module download it again. Also please assure, that you are using the most recent version of django-tailwind-cli. Older versions once had the issue, that they mixed up for which architecture to download the cli.

**Comment by naresh-kapsus** [comment]
Ok, I will try it

**Comment by oliverandrich** [comment]
@naresh-kapsus if it happens again. Please don't hesitate to reopen this issue.
